In [ ]:
f1 = open("data/1.html", "r")
html1 = f1.read()
f2 = open("data/2.html", "r")
html2 = f2.read()
html1 == html2

True

In [ ]:
f = open("_.html", "r")
html = f.read()
print(html[:1000])

<html lang="">
 <head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width,initial-scale=1" name="viewport"/>
  <link href="favicon.ico" rel="icon"/>
  <title>
   Air4Thai
  </title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
  <link href="./fontawesome-6/css/all.css" rel="stylesheet"/>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-LQ0X6LTJCP">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-LQ0X6LTJCP');
  </script>
  <link href="css/chunk-0d999424.54c228f4.css" rel="prefetch"/>
  <link href="css/chunk-11c017e9.09210bf8.css" rel="prefetch"/>
  <link href="css/chunk-2cd1134a.624f37fb.css" rel="prefetch"/>
  <link href="css/chunk-2dba504c.f2e776f5.css" rel="prefetch"/>
  <link href="css/chunk-35e7

In [6]:
import pandas as pd
from bs4 import BeautifulSoup

# Assuming `html` contains the raw HTML you extracted earlier
soup = BeautifulSoup(html, 'html.parser')

# Find the table in the HTML (by id, class, etc.)
table = soup.find('table', {'id': '__BVID__57'})

# Extract the table headers
headers = [th.get_text(strip=True) for th in table.find_all('th')]

# Extract the rows of the table
rows = []
for tr in table.find_all('tr')[1:]:  # Skip the header row
    cols = tr.find_all('td')
    row = [col.get_text(strip=True) for col in cols]
    rows.append(row)

# Create a DataFrame
df = pd.DataFrame(rows, columns=headers)

# Show the DataFrame
df

   No.      วันที่ ช่วงเวลา   03t
0    1  2025-02-17    01:00  25.9
1    2  2025-02-17    02:00  21.4
2    3  2025-02-17    03:00  20.3
3    4  2025-02-17    04:00  23.4
4    5  2025-02-17    05:00  24.8
5    6  2025-02-17    06:00  27.1
6    7  2025-02-17    07:00  30.5
7    8  2025-02-17    08:00  34.6
8    9  2025-02-17    09:00  35.5
9   10  2025-02-17    10:00  31.4
10  11  2025-02-17    11:00  32.2
11  12  2025-02-17    12:00  30.7
12  13  2025-02-17    13:00  32.7
13  14  2025-02-17    14:00  33.3
14  15  2025-02-17    15:00  31.1
15  16  2025-02-17    16:00  32.2
16  17  2025-02-17    17:00  29.1
17  18  2025-02-17    18:00  32.8
18  19  2025-02-17    19:00  31.9
19  20  2025-02-17    20:00  29.2